server:
  port: 8081
  error:
    whitelabel:
      enabled : false
spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  http:
    multipart:
    max-file-size: 5MB
    max-request-size: 20MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      additional-paths: .



